services:
  subscription-api:
    build:
      context: .
      dockerfile: Subscriptions/Dockerfile
    container_name: subscription-api
    depends_on:
      - subscriptions-db
    ports:
      - "8016:8016"
    restart:
      always

  subscriptions-db:
    image: mysql:8.0
    container_name: subscriptions-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: subscriptions
    ports:
      - "3311:3306"
    restart:
      always