services:
  profiles-api:
    image: profiles
    container_name: profiles-api
    ports:
      - "8015:8015"
    build:
      context: .
      dockerfile: Profiles/Dockerfile
    depends_on:
      - profiles-db
    restart:
      always
  
  profiles-db:
    image: mysql:8.0
    container_name: profiles-db
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: profiles
    restart:
      always
